Repository AlexJuca/grepru, pull requests merged in 2020-09, with the labels that each got.

#11 Remove warning from BufRead
  src/lib.rs
  words.txt
Labels: enhancement

#12 Print count feature
  Cargo.lock
  Cargo.toml
  src/lib.rs
  tests/cli.rs
Labels: enhancement

#14 Count single chars found
  README.md
  src/lib.rs
  tests/cli.rs
Labels: documentation

#13 add documentation for new functionality to readme
  README.md
Labels: documentation

#15 implemented functionality to find a pattern in given text and print i…
  src/lib.rs
  tests/cli.rs
Labels: enhancement

#16 updated module structure
  src/cli.rs
  src/cli/cli.rs
  src/cli/mod.rs
  src/main.rs
  src/text/mod.rs
  src/text/text.rs
Labels: enhancement

#18 New docs and improvements
  Cargo.lock
  Cargo.toml
  README.md
  images/line-number.png
  src/text/text.rs
  tests/cli.rs
Labels: documentation, enhancement
